In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

style_name = 'bmh' #bmh
mpl.style.use(style_name)
np.set_printoptions(precision=4, linewidth =150)

style = plt.style.library[style_name]
style_colors = [ c['color'] for c in style['axes.prop_cycle'] ]

### 1. 다음을 수행하는 파이썬 함수를 작성하여 보세요.

- 리스트를 넘겨 받아 리스트에 저장된 숫자중 가장 큰값과 가장 작은값의 평균을 리턴

- 리스트의 최대, 최소값을 위해 <span class="code-body">max()</span>, <span class="code-body">min()</span> 함수를 사용하세요.

In [2]:
###################################################
# pass로 표시된 곳에 적절히 코드를 써 넣으세요.
###################################################
def avg(l):
    return (max(l) + min(l)) / 2
#     return pass


print(avg([1,2,3,4,5]))

3.0


In [3]:
# import numpy
# ###################################################
# # pass로 표시된 곳에 적절히 코드를 써 넣으세요.
# ###################################################
# def avg(l):
#     l_mean = np.mean((max(l) + min(l)))
#     return l_mean

# print(avg([1,2,3,4,5]))


### 2. 구구단을 아래와 같이 출력하는 함수 times_table(k)를 작성하세요.

- k : 출력할 구구단의 숫자가 저장된 리스트 예: [2,4,5]

<pre>
2x1 =  2   3x1 =  3   4x1 =  4   5x1 =  5   6x1 =  6   7x1 =  7   8x1 =  8   9x1 =  9   
2x2 =  4   3x2 =  6   4x2 =  8   5x2 = 10   6x2 = 12   7x2 = 14   8x2 = 16   9x2 = 18   
2x3 =  6   3x3 =  9   4x3 = 12   5x3 = 15   6x3 = 18   7x3 = 21   8x3 = 24   9x3 = 27   
2x4 =  8   3x4 = 12   4x4 = 16   5x4 = 20   6x4 = 24   7x4 = 28   8x4 = 32   9x4 = 36   
2x5 = 10   3x5 = 15   4x5 = 20   5x5 = 25   6x5 = 30   7x5 = 35   8x5 = 40   9x5 = 45   
2x6 = 12   3x6 = 18   4x6 = 24   5x6 = 30   6x6 = 36   7x6 = 42   8x6 = 48   9x6 = 54   
2x7 = 14   3x7 = 21   4x7 = 28   5x7 = 35   6x7 = 42   7x7 = 49   8x7 = 56   9x7 = 63   
2x8 = 16   3x8 = 24   4x8 = 32   5x8 = 40   6x8 = 48   7x8 = 56   8x8 = 64   9x8 = 72   
2x9 = 18   3x9 = 27   4x9 = 36   5x9 = 45   6x9 = 54   7x9 = 63   8x9 = 72   9x9 = 81 
</pre>

In [4]:
###################################################
# pass로 표시된 곳에 적절히 코드를 써 넣으세요.
###################################################

def times_table(K) :
    # 구구단에서 뒤쪽 숫자 1~9까지 루프를 돌면서
    for pass :
        row = ""
        
        # 구구단에서 k단에 대해서
        for k in K :
            # 출력의 한 행을 만든다.
            row += pass
            
            #구구단 사이의 빈 간격
            row += "   " 
            
        # 한줄 다 만들었으면 출력한다.    
        print(row)
            
times_table([2,3,4,5,6,7,8,9])        

SyntaxError: invalid syntax (<ipython-input-4-016b9e0244f8>, line 7)

### 3. 소수 구하기 

- 소수는 1과 자기 자신만을 약수로 가지는 자연수입니다.

- 에라토스테네스의 체라는 방법은 2부터 숫자 N사이에 있는 소수를 찾아내기 위해 2를 제외한 2의 배수를 다 지우고, 3을 제외한 3의 배수를 다지우는 방식으로 소수만을 남기는 방법입니다. 

- 2에서 1000까지 수중에 소수는 구하는 프로그램을 다음과 같은 방법으로 작성해보세요.

    - 1) 리스트 컴프리헨션을 사용하여 <span class="code-body">[2, 3, 4, 5, 6, ..., 1000]</span> 인 리스트를 N에 저장한다. 

    - 2) 2에서 1000까지 c라는 변수로 for 루프를 돌면서 
    
    - 3) 리스트 컴프리헨션을 사용하여 N에 속하는 i들에 대해서 c보다 작거나, c보다 크다면 c의 배수가 아닌 수 만을 리스트에 담는다. 즉, 다음 조건문을 사용한다.
    ```python
        for i in N if i <= c or i % c != 0
    ```

- 다음 리스트가 출력되는지 확인한다.
    
    - <span class="code-body">[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]</span>
    
    - <span class="code-body">print(len(N)) # 결과 168 </span>

- 아래 코드에 풀이가 있으니 풀이를 보고 상황을 이해할 수 있게 생각해봅시다.

In [ ]:
# 단계 1
N = [ i for i in range(2,1001)]

# 단계 2
for c in range(2, 1001):
    # 단계 3
    N = [i for i in N if i <= c or i % c != 0]

print("Prime numbers")
print(N)
print("\n")
print("# of prime numbrs : {}".format(len(N)))

### 4. numpy 어레이 조작

- 구구단의 결과를 다음처럼 저장하는 3차원 어레이를 만들어 봅시다. 단, for문을 쓰지말고

<pre>
[[[ 2  1  2]
  [ 2  2  4]
  [ 2  3  6]
  [ 2  4  8]
  [ 2  5 10]
  [ 2  6 12]
  [ 2  7 14]
  [ 2  8 16]
  [ 2  9 18]]

 [[ 3  1  3]
  [ 3  2  6]
  [ 3  3  9]
  [ 3  4 12]
  [ 3  5 15]
  [ 3  6 18]
  [ 3  7 21]
  [ 3  8 24]
  [ 3  9 27]]
  
  ...
  
 [[ 9  1  9]
  [ 9  2 18]
  [ 9  3 27]
  [ 9  4 36]
  [ 9  5 45]
  [ 9  6 54]
  [ 9  7 63]
  [ 9  8 72]
  [ 9  9 81]]]
</pre>

- 아래 코드에 풀이가 있으니 풀이를 보고 상황을 이해할 수 있게 생각해봅시다.

In [ ]:
A = np.arange(1,10)

B = np.tile(A,9).reshape(-1,9)
C = B[:,1:] # 구구단 앞 숫자 
D = B.T[:,1:] # 구구단 뒷 숫자
E = (A.reshape(-1,1)*A)[:,1:] # 구구단 결과

# 한줄로 펴서 각 줄을 가로 한줄로 해서 3행짜리 행렬을 만들어 전치
F = np.array([C.T.flatten(), D.T.flatten(), E.T.flatten()]).T

print(F.shape)
print('\n')

# F는 구구단 결과를 순차적으로 저장하고 있는 2차원 어레이
print(F)
print('\n')

# 단별로 잘라서 3차원 어레이로 만든다.
print(F.reshape(8,9,-1))

- 이번에는 위 문제의 결과로 나온 어레이를 조작해서 구구단의 결과를 다음처럼 저장하는 3차원 어레이를 만들어 봅시다. 

<pre>
[[[ 2  1  2]
  [ 3  1  3]
  [ 4  1  4]
  [ 5  1  5]
  [ 6  1  6]
  [ 7  1  7]
  [ 8  1  8]
  [ 9  1  9]]

 [[ 2  2  4]
  [ 3  2  6]
  [ 4  2  8]
  [ 5  2 10]
  [ 6  2 12]
  [ 7  2 14]
  [ 8  2 16]
  [ 9  2 18]]
  
  ...
  
 [[ 2  9 18]
  [ 3  9 27]
  [ 4  9 36]
  [ 5  9 45]
  [ 6  9 54]
  [ 7  9 63]
  [ 8  9 72]
  [ 9  9 81]]]
</pre>

In [ ]:
# 단별로 잘라서 3차원 어레이로 만들고, 전치를 적당히 시켜서 *1, *2, ... , *9끼리 모은다.
print(F.reshape(8,9,-1).transpose(1,0,2))

### 5. 종합 문제 K-mean clustering

In [ ]:
import pandas as pd

plt.rcParams["figure.figsize"] = (15,5)

faithful = pd.read_csv('faithful.csv')
faithful.head()

faithful = (faithful - faithful.mean()) / faithful.std()
faithful.columns = ['eruptions', 'waiting']

fig, (ax1, ax2) = plt.subplots(1, 2)

ax1.scatter(faithful.eruptions, faithful.waiting)
ax1.set_title('Old Faithful Data Scatterplot')
ax1.set_xlabel('Length of eruption (minutes)')
ax1.set_ylabel('Time between eruptions (minutes)')

centroids = np.array([[-1.3, 1.0], [1.2, -1.0]])
ax2.scatter(faithful.eruptions, faithful.waiting)
ax2.plot(centroids[0,0], centroids[0,1], 'bx', markersize=10, markeredgewidth=5)
ax2.plot(centroids[1,0], centroids[1,1], 'rx', markersize=10, markeredgewidth=5)
plt.show()

faith = np.array(faithful)
k = 2

print(faith.shape)

- 위 그림은 미국 Yellowstone 국립 공원의 유명한 간헐천(間歇泉)의 분출 지속시간과 분출간의 시간차를 나타낸 것이다.

- http://www.stat.cmu.edu/~larry/all-of-statistics/=data/faithful.dat

- 그래프상 분출과 분출사이의 간격이 길수록 오래동안 분출하는 것처럼 보인다.

- 분출사이의 간격과 분출 지속시간을 두 그룹으로 묶어볼 수 있을 것 같다.

- 오른쪽 그래프처럼 두 묶음의 중심(파란색, 빨간색)을 아무렇게나 찍은 다음 다음 절차를 통해 묶음 작업을 진행하고자 한다.

    - 1) 그림처럼 초기 중심점을 2개 아무렇게나 찍는다.
    - 2) 모든 데이터에 대해서 초기 중심점과의 간격을 계산하여 더 가까운쪽의 묶음으로 데이터를 할당한다.
    - 3) 위 작업이 완료되면 두 묶음으로 분리된 데이터의 평균점을 구한다.
    - 4) 계산된 평균점을 새로운 점으로 하여 2의 과정으로 돌아가 반복한다.

- 위 같은 반복을 5회한 후 다음과 같은 그림을 얻게 된다.

<img src="imgs/hw1.png"/>

- 이 과정은 K-mean clustering 알고리즘으로 알려져있고 구현은 다음과 같습니다.

- 주석을 참고하여 pass라고 되어 있는 곳에 적당한 코드를 완성하세요.

In [ ]:
# 주의 : 이 셀을 실행시키기 전에 반드시 윗 셀을 먼저 실행시켜 데이터를 로드하고 실행하여야 함. 

###################################################
# pass로 표시된 곳에 적절히 코드를 써 넣으세요.
###################################################

plt.rcParams["figure.figsize"] = (8,5)

# 클러스터링 과정을 5회 반복한다.
for i in range(5):
    # faith에 저장된 272개의 점에 대해 각각 점이 클러스터 0인지 클러스터 1인지를 기록하는 2차원 어레이
    # 아래처럼 272행 k(클러스터 수)열인 2차원 어레이
    #
    # rnk 어레이는 다음처럼 행번호에 해당하는 점이 열번호에 해당하는 묶음에 할당되면 1, 아니면 0으로 표시한다.
    #
    # rnk = [ [1, 0],      첫번째 점은 0번 묶음이다.
    #         [0, 1],      두번째 점은 1번 묶음이다.
    #         ...   ,
    #         ...   ,
    #         [1, 0] ]     272번째 점은 0번 묶음이다.
    #
    # 처음에는 모두 0으로 초기화
    rnk = np.zeros( (pass) )
    
    # 1) 모든 데이터에 대해서 초기 중심점과의 간격을 계산하여 더 가까운쪽의 묶음으로 데이터를 할당한다.
    # 각점이 어느 클러스터에 속하는지 rnk 어레이에 표시한다.
    for n in range(faith.shape[0]):
        # n번째 데이터 포인트를 x에 받아와서
        x = faith[n]
        
        # 현재 중심점 2개 centroids[0]와 centroids[1]간의 거리를 구해서 비교한다.
        # 초기 중심점은 다음처럼 윗셀에서 초기화 했다.
        # centroids = np.array([[-1.3, 1.0], [1.2, -1.0]])
        # 각 중심점에서 x까지 거리를 구하는 법 : np.linalg.norm(x-centroids[0]), np.linalg.norm(x-centroids[1])
        if pass : 
            rnk[n,0] = 1
        else :
            rnk[n,1] = 1
    
    # 그림을 그리기위해 faith에 저장된 점데이터를 파랑과 빨강으로 분류 한다.
    # 앞서 만든 rnk 어레이의 상태에 따라 두 부분으로 나눈다.
    blue = faith[np.where(rnk[:,0]==1)]
    red  = faith[np.where(rnk[:,1]==1)]
    
    ##########################################################################################
    # 2) 위 작업이 완료되면 두 묶음으로 분리된 데이터의 평균점을 구한다.
    # 힌트 : 지금 두 묶음은 위의 blue, red 어레이에 각각 들어가 있고
    # blue 어레이에 저장된 점의 평균을 centroids[0]에 할당하고
    # red 어레이에 저장된 점의 평균을 centroids[1]에 할당한다.
    # 어레이의 평균을 구하기 위해서는 mean 함수를 사용한다.
    # mean함수 문서 : https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.mean.html
    centroids[0] = pass
    centroids[1] = pass
    
    # 한번 반복 후 클러스터링 상황을 그린다.
    plt.plot(blue[:,0], blue[:,1],'o', markersize=7, alpha=0.7)
    plt.plot(red[:,0],  red[:,1], 'o', markersize=7, alpha=0.7) 
    plt.plot(centroids[0,0], centroids[0,1], 'bx', markersize=10, markeredgewidth=5)
    plt.plot(centroids[1,0], centroids[1,1], 'rx', markersize=10, markeredgewidth=5)   

    plt.show()

In [ ]:
%%html
<link href='https://fonts.googleapis.com/earlyaccess/notosanskr.css' rel='stylesheet' type='text/css'>
<!--https://github.com/kattergil/NotoSerifKR-Web/stargazers-->
<link href='https://cdn.rawgit.com/kattergil/NotoSerifKR-Web/5e08423b/stylesheet/NotoSerif-Web.css' rel='stylesheet' type='text/css'>
<!--https://github.com/Joungkyun/font-d2coding-->
<link href="http://cdn.jsdelivr.net/gh/joungkyun/font-d2coding/d2coding.css" rel="stylesheet" type="text/css">
<style>
    h1     { font-family: 'Noto Sans KR' !important; color:#348ABD !important;   }
    h2     { font-family: 'Noto Sans KR' !important; color:#467821 !important;   }
    h3, h4 { font-family: 'Noto Sans KR' !important; color:#A60628 !important;   }
    p:not(.navbar-text) { font-family: 'Noto Serif KR', 'Nanum Myeongjo'; font-size: 12pt; line-height: 200%;  text-indent: 10px; }
    li:not(.dropdown):not(.p-TabBar-tab):not(.p-MenuBar-item):not(.jp-DirListing-item):not(.p-CommandPalette-header):not(.p-CommandPalette-item):not(.jp-RunningSessions-item)
            { font-family: 'Noto Serif KR', 'Nanum Myeongjo'; font-size: 12pt; line-height: 200%; }
    table  { font-family: 'Noto Sans KR' !important;  font-size: 11pt !important; }           
    li > p  { text-indent: 0px; }
    li > ul { margin-top: 0px !important; }       
    sup { font-family: 'Noto Sans KR'; font-size: 9pt; } 
    code, pre  { font-family: D2Coding, 'D2 coding' !important; font-size: 12pt !important; line-height: 130% !important;}
    .code-body { font-family: D2Coding, 'D2 coding' !important; font-size: 12pt !important;}
    .ns        { font-family: 'Noto Sans KR'; font-size: 15pt;}
    .summary   {
                   font-family: 'Georgia'; font-size: 12pt; line-height: 200%; 
                   border-left:3px solid #FF0000; 
                   padding-left:20px; 
                   margin-top:10px;
                   margin-left:15px;
               }
    .green { color:#467821 !important; }
    .comment { font-family: 'Noto Sans KR'; font-size: 10pt; }
</style>