In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

a + b

array([ 6,  8, 10, 12])

In [9]:
aa = np.ones((3, 3))
aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
aa + aa

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [11]:
aa*aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
aaa = np.matrix(aa)

In [13]:
aaa*aaa

matrix([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [15]:
np.dot(aa, aa)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])